# Site settings
title: Jaeil Park's Blog
description: A DevSecOps blog by Jaeil Park
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jaeil Park
user_description: DevSecOps Engineer  
user_title: DevSecOps Engineer
email: jaeilpark@suwon.ac.kr
twitter_username: .
github_username: parkjaeil0x01
gplus_username: .

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
